# Generated by Django 2.1 on 2018-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20180915_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
